import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import RootHeader from "@/components/Header";
import RootFooter from "@/components/Footer";
import React from "react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Un site dont vous êtes l'héro-ine",
	description: "Generated by create next app",
};

export default function RootLayout({
	info,
	children,
}: Readonly<{
	info: React.ReactNode;
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} min-h-screen flex flex-col mx-auto`}>
				<RootHeader />
				<Link href="/character">Open</Link>
				<div>{info}</div>
				<div>{children}</div>
				<RootFooter />
			</body>
		</html>
	);
}
